### ISSUE TITLE
无显卡主机　安装　Macos 13　错误

### ISSUE THREAD

**Issue by sunof-top** [theofficialcopypaste/ihackmsimagb460tomahawk#3]
你好，非常感谢你的OC！
但是我并未安装成功 Macos 13
具体，请看图片，我是没有显卡的主机，使用的是DP
![IMG_20230213_171049](https://user-images.githubusercontent.com/69024415/218424588-6f958b3e-94d5-41f6-9c23-b8cc9a88765e.jpg)
![IMG_20230213_172930](https://user-images.githubusercontent.com/69024415/218424610-73d3652d-d190-4b84-8f37-5d256fdddfff.jpg)
![IMG_20230213_173245](https://user-images.githubusercontent.com/69024415/218424621-e51b7e20-46b9-41bd-9082-a01ea8b57070.jpg)

**Comment by theofficialcopypaste** [comment]
without dgpu?

**Comment by sunof-top** [comment]
没有gpu

**Comment by theofficialcopypaste** [comment]
without any gpu, you unable to boot. at least iGPU (UHD630)

**Comment by sunof-top** [comment]
是的 我是使用的是10400 有 UHD630

**Comment by theofficialcopypaste** [comment]
im working this day, i will respond soon as possible

**Comment by sunof-top** [comment]
谢谢

**Comment by theofficialcopypaste** [comment]
recommend you to check this, https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore

**Comment by sunof-top** [comment]
感谢指导，但是本人能力有限，没有成功，/(ㄒoㄒ)/~~
